server:
  port: 40002
spring:
  application:
    name: hello-kafka-consumer
  kafka:
    # ????
    bootstrap-servers: 127.0.0.1:9092
    # 生产者配置
    producer:
      # 重试次数
      retries: 3
      # 应答级别
      # acks=0 把消息发送到kafka就认为发送成功
      # acks=1 把消息发送到kafka leader分区，并且写入磁盘就认为发送成功
      # acks=all 把消息发送到kafka leader分区，并且leader分区的副本follower对消息进行了同步就任务发送成功
      acks: all
      # 批量处理的最大大小 单位 byte
      batch-size: 4096
      # 发送延时,当生产端积累的消息达到batch-size或接收到消息linger.ms后,生产者就会将消息提交给kafka
      buffer-memory: 33554432
      # 客户端ID
      client-id: hello-kafka
      # Key 序列化类
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Value 序列化类
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息压缩：none、lz4、gzip、snappy，默认为 none。
      compression-type: gzip
      properties:
        partitioner:
          #指定自定义分区器
          class: top.zysite.hello.kafka.partitioner.MyPartitioner
        linger:
          # 发送延时,当生产端积累的消息达到batch-size或接收到消息linger.ms后,生产者就会将消息提交给kafka
          ms: 1000
        max:
          block:
            # KafkaProducer.send() 和 partitionsFor() 方法的最长阻塞时间 单位 ms
            ms: 6000
    listener:
      #??????????? single?????batch????
      type: batch
    # ?????
    consumer:
      # ??????
      group-id: testGroup
      # ???? offset ?? true
      enable-auto-commit: false
      # ??????? ?? ms
      auto-commit-interval: 1000
      # ????????
      max-poll-records: 100
      # Key ?????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Value ?????
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # ?kafka?????offset?offset??????????offset
      # earliest:?????????offset
      # latest:?????????offset(???????????)
      # none:??????????????offset,?????
      auto-offset-reset: latest
      properties:
        interceptor:
          classes: top.zysite.hello.kafka.interceptor.MyConsumerInterceptor
        session:
          timeout:
            # session?????????consumer??????,????rebalance??
            ms: 120000
        request:
          timeout:
            # ????
            ms: 120000